Rfc: bin/mnt

diff --git a/bin/mnt b/bin/mnt
--- a/bin/mnt
+++ b/bin/mnt
@@ -11,49 +11,50 @@ source ~/.shell/profile
 # https://ru.wikipedia.org/wiki/Mount
 
 # Disk mounting util
-if [[ -n "$1" && ${#1} -le 2 ]]; then ACTION="${1}"; shift; else ACTION="m"; fi
+if [[ -n $1 && ${#1} -le 2 ]]; then ACTION=$1; shift; else ACTION=m; fi
 
-LBL="${1}"
-MNT="/media/${CURR_USER:-`whoami`}"
-DIR="$MNT/$LBL"
+LBL=$1
+MNT=/media/${CURR_USER:-`whoami`}
+DIR=$MNT/$LBL
 
 if [[ -z "$LBL" ]]; then
     printf "LABELS: " && (cd /dev/disk/by-label 2>/dev/null && ls --color=auto || echo)
-    printf "DISKS: " && (cd /dev && ls sd?[0-9] 2>/dev/null || echo)
-    printf "SAMBA: " && (sed -rn '/^\s+(\w+)\)\s+dosamba.*/s//\1/p' "$0" | xargs || echo)
-    printf "ACTIVE: " && ls --color=auto "$MNT"
+    printf "DISKS:  " && (cd /dev && ls sd?[0-9] 2>/dev/null || echo)
+    printf "SAMBA:  " && (sed -rn '/^\s+(\w+)\)\s+dosamba.*/s//\1/p' "$0" | xargs || echo)
+    printf "ACTIVE: " && (ls --color=auto "$MNT") && echo || echo
     exit
 fi
 
-die() { printf "%s\n" "$@"; exit 1; }
-check() { grep -qsw "$DIR" /proc/mounts && die "Already mounted at '$DIR'!"; }
-clean() { check; if [ -d "$DIR" ]; then
-rmdir "$DIR" 2>/dev/null ||
-    sudo rmdir -v "$DIR" || die "Can't remove directry '$DIR'!"
-fi; }
-dirmk() { clean; mkdir -p "$DIR" 2>/dev/null ||
-    sudo mkdir -p "$DIR" && sudo chown $CURR_USER:$CURR_USER "$DIR" || die "Error: Can't create directory for mount!"
+die() { printf "%s\n" "$*"; exit 1; }
+check() { grep -qsw "$1" /proc/mounts && die "Already mounted at '$1'!"; }
+clean() { check "$1"
+  [[ -d $1 ]] || return 0
+  rmdir "$1" 2>/dev/null \
+  || sudo rmdir -v "$1" \
+  || die "Can't remove directory '$1'!"
+}
+chuser(){ sudo chown "$CURR_USER:$CURR_USER" "$1"; }
+dirmk() { clean "$1"
+  mkdir -p "$1" 2>/dev/null \
+  || sudo mkdir -p "$1" && chuser "$1" \
+  || die "Error: Can't create directory '$1'for mount!"
 }
 
 
 # Need package 'jmtpfs', unmount by fusermount -u "$DIR"
-domtp() { dirmk && jmtpfs "$DIR"; }
-doram() { dirmk && sudo mount -t ramfs -o size=100m ramfs "$DIR" &&
-        sudo chown "$CURR_USER:$CURR_USER" "$DIR"; }
-dosamba() {
-    dirmk && sudo mount -t cifs -o user="${1?Need user}" "//${2?Need share}/" "$DIR" \
-        && sudo chown "$CURR_USER:$CURR_USER" "$DIR" && echo "$DIR" || exit
+domtp() { dirmk "$1" && jmtpfs "$1"; }
+doram() { dirmk "$1" && sudo mount -t ramfs -o size=100m ramfs "$1" && chuser "$1"; }
+dosamba() { dirmk "$1" \
+  && sudo mount -t cifs -o user="${2:?No user}" "//${3:?No share}/" "$1" \
+  && chuser "$1" && echo "$1" || exit
 }
-doloop() {  # You must launch it from iso's directory!
-    DEVPATH="$PWD/$LBL"
-    if ! [ -e "$DEVPATH" ]; then die "Error: no such file '$DEVPATH'"; fi
-    dirmk && sudo mount -o loop,ro "$DEVPATH" "$DIR" || exit
+doloop() { local DEVPATH=$PWD/$LBL
+    [[ -f $DEVPATH ]] || die "Error: no such file '$DEVPATH'"
+    dirmk "$1" && sudo mount -o loop,ro "$DEVPATH" "$1" || exit
 }
-domnt() {
-    local DEVPATH TYPE
-    DEVPATH="/dev/disk/by-label/$LBL"
-    if [[ ! -L "$DEVPATH" ]]; then DEVPATH="/dev/$LBL"; fi
-    if [[ ! -e "$DEVPATH" ]]; then die "No device at path"; fi
+domnt() { local TYPE DEVPATH=/dev/disk/by-label/$LBL
+    [[ -L $DEVPATH ]] || DEVPATH=/dev/$LBL
+    [[ -e $DEVPATH ]] || die "No device at path"
 
     # Flash drive:  http://linuxsam.livejournal.com/18176.html
 
@@ -67,23 +68,25 @@ codepage=437,iocharset=iso8859-1,shortname=mixed,showexec,utf8,flush,errors=remo
     ;;    *) die "Unknown type '$TYPE'" ;; esac
     # -t "$TYPE"
     echo $MOPTS
-    dirmk && sudo mount "$DEVPATH" "$DIR" ${MOPTS:+-o $MOPTS} \
-        && sudo chown "$CURR_USER:$CURR_USER" "$DIR" && echo "$DIR" || exit
+    dirmk "$1" && sudo mount "$DEVPATH" "$DIR" ${MOPTS:+-o $MOPTS} \
+        && chuser "$DIR" && echo "$DIR" || exit
 }
 
 
 case "$ACTION" in
  m) domnt ;;
- a) domtp ;;
- r) doram ;;
- o) doloop ;;
+ a) domtp "$DIR" ;;
+ r) doram "$DIR" ;;
+ o) doloop "$DIR" ;;  # You must launch it from iso's directory!
  s) case "${LBL:?}" in
     # smbclient -L 192.168.1.1
-     android) dosamba ${ANDR_USER:?} ${ANDR_IPL:?} ;;
-      router) dosamba ${ROUT_USER:?} ${ROUT_IPL:?}/share ;;
+     android) dosamba "$DIR" ${ANDR_USER:?} ${ANDR_IPL:?} ;;
+      router) dosamba "$DIR" ${ROUT_USER:?} ${ROUT_IPL:?}/share ;;
+        home) dosamba "$DIR" ${LAPT_USER:?} ${LAPT_IPL:?}/home ;;
+       media) dosamba "$DIR" ${LAPT_USER:?} ${LAPT_IPL:?}/media ;;
     esac ;;
- u) sudo umount -v "$DIR"; clean || exit ;;
-#U) sudo umount -v -R "$MNT"/* && sudo rmdir -v "$MNT"/* ;;  # ERROR: No -R key
+ u) sudo umount -v "$DIR"; clean "$DIR" || exit ;;
+ U) sudo umount -v "$MNT"/* ||:; sudo rmdir -v "$MNT"/* ;;
  i) sudo blkid ;;  # Get table disk/label/filesystems
  *) echo "Error: '$ACTION'" ;;
 esac
