[airy] restore ./install working as-is

diff --git a/airy/shell/func.d/packages b/airy/shell/func.d/packages
--- a/airy/shell/func.d/packages
+++ b/airy/shell/func.d/packages
@@ -4,6 +4,17 @@ source ~/.shell/func.d/system
 trap_errors
 cwd_script
 
+# HACK: install packages manually by ./install
+if [[ -z ${LISTS_STORE_DIR-} ]]; then
+  export AIRY_TMPDIR="${TMPDIR:-/tmp/${LOGNAME:?}}/airy"
+  export LISTS_STORE_DIR="$AIRY_TMPDIR/manual"
+  mkdir -p "$LISTS_STORE_DIR" "$AIRY_TMPDIR/ts"
+  # BAD:HACK: cleanup prev lists to install only current "install"
+  find "$LISTS_STORE_DIR" -maxdepth 1 -type f -regextype egrep -regex '.*/(aur|loc|pkg).(list|deps)$' -delete
+  # [[ -t 1 ]] && exec > >(r.airy-pretty)
+  trap "r.airy-mods-make tsdir='$AIRY_TMPDIR/ts' flags=-mu '${PWD##*/}'" EXIT
+fi
+
 # Re-install even if git pull is up-to-date (for broken builds)
 # u=update U=update_always
 while getopts 'mrsuU' o; do case $o in :|'?') die 1
