FIX vim setup -- log of plugin updates

diff --git a/cfg/term/vim/setup b/cfg/term/vim/setup
--- a/cfg/term/vim/setup
+++ b/cfg/term/vim/setup
@@ -59,11 +59,14 @@ fi
 
 ### PLUGINS ###
 if cfgOpt u || [[ ! -d "$VCACHE/bundle" ]]; then
+    # BUG: returns non-zero errcode!
     # FIXME: error on clean system, when NeoBundle is not installed yet
-    $EDITOR -E -X -R -i NONE -c "set nomore" +NeoBundleClearCache +qall </dev/tty ||:
-    $EDITOR -E -X -R -i NONE -c "set nomore" +NeoBundleUpdate\! +qall </dev/tty ||:
-    ! has_pr nvim || nvim -E -X -R -i NONE -c "set nomore" \
-        +UpdateRemotePlugins +qall </dev/tty ||:
+    shvim() { $EDITOR -nesR -i NONE -u "$PWD/vimrc" \
+        -c "set nomore|redir!>/dev/stderr" -c "$1" \
+        -c "echo''|redir END|qall!" >/dev/null ||:; }
+    shvim 'NeoBundleClearCache'
+    shvim 'NeoBundleUpdate!'
+    ! has_pr nvim || shvim 'UpdateRemotePlugins'
 fi
 
 ### PLUG-RC ###
