Fix: clean system. TODO:FIXME:(investigate marks)

diff --git a/cfg/shell/func.d/cfgsetup b/cfg/shell/func.d/cfgsetup
--- a/cfg/shell/func.d/cfgsetup
+++ b/cfg/shell/func.d/cfgsetup
@@ -2,6 +2,7 @@
 source ~/.shell/profile
 source ~/.shell/func.d/system
 trap_errors
+export PATH=${CURR_DIR_CACHE:?}/bin:$PATH
 
 ### Argparse ###
 CFG_ARGS=( "$@" )  # Backup default arguments
@@ -15,18 +16,20 @@ in t) THEME=$OPTARG
 esac; cfgOptAdd "$o"; done; shift $((OPTIND - 1))
 
 ### Choose theme
-[[ $THEME ]] || THEME=$(<"${CURR_DIR_CACHE:?}/theme")
 [[ $THEME_ALLOWED ]] || THEME_ALLOWED='dark|light|lucid|opaque'
+[[ $THEME ]] || THEME=$(<"${CURR_DIR_CACHE:?}/theme") ||:
 [[ $THEME =~ ^($THEME_ALLOWED)$ ]] || THEME=dark
 
 
 ### LINKS ###
+# BUG: on error we can't exit from forked shell and fail main one!
 fork_m(){ cfgOpt m && eval '"$@" &' || "$@"; }
-link(){ ~/.bin/prg.d/linkcp $@; }
+link(){ ~/.bin/prg.d/linkcp "$@"; }
 ### Populate all run, run.pr1 scripts into mycache/bin
 linkmask(){ local nm mask=$1 fmt=$2
-  [[ -z $PS1 && $0 =~ ^${CURR_DIR_CFG:?} ]] || return 0
-  for src in "$mask"*; do [[ -f "$src" && -x "$src" ]] || continue
+  # ALT:(-m) -z $PS1 -- BUT: we can't manually activate mod
+  cfgOpt m && [[ $0 =~ ^${CURR_DIR_CFG:?} ]] || return 0
+  for src in "$mask"*; do [[ -f $src && -x $src ]] || continue
     nm=$(printf "$fmt" "${PWD##*/}" "${src#$mask}")
     link "$src" "$CURR_DIR_CACHE/$nm"
   done
@@ -34,7 +37,9 @@ linkmask(){ local nm mask=$1 fmt=$2
 
 
 if distro arch; then
-  mkdef() { link "${2:?No bin}" "$CURR_DIR_CACHE/bin/${1:?No name}"; }
+  # TODO:DEV: add fallback -- for each arg until pr found OR err
+  mkdef() { link "$(which "${2:?No bin}")" \
+    "$CURR_DIR_CACHE/bin/${1:?No name}"; }
   svc_enable() { systemctl is-enabled "$1" > /dev/null || sudo systemctl enable "$1"; }
   svc_disable() { systemctl is-enabled "$1" > /dev/null || return 0; sudo systemctl disable "$1"; }
   svc_restart() { sudo systemctl restart "$1"; }
@@ -57,7 +62,7 @@ fi
 
 ### Go to current script's directory
 cd $(dirname $(readlink -m ${0}))
-[[ -n "$MODS_CACHE_DISABLE" ]] || airy_cache_pwd_mod
+[[ $MODS_CACHE_DISABLE ]] || airy_cache_pwd_mod
 
 if [[ -z $MODS_RUN_DISABLE ]]; then
   linkmask "$PWD/bin/" 'bin/r.%s-%s'
diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -10,25 +10,6 @@ mods="$CURR_DIR_CACHE/mods/mods" && mkdir -p "${mods%/*}"
 export PATH=~/.bin:$PATH
 
 # ======================================================================
-# THINK:USE: exec > >(pretty)  (BUT: pacman -Syu output, etc?)
-for n in {0..15}; do declare C${n}=$(tput setaf ${n:?}); done && CR=$(tput sgr0)
-header(){ printf "\n$C2>>> %s <<<$CR\n" "$1"; }
-pretty() { sed -r "
-  s|/home/$(whoami)|\~|g
-  s|\~/\S+/cfg/||g
-  />>>/!s|^|  |g
-  /^>>> \~\/aura\//s//\n$C9\[/g
-  /^>>> /s//\n$C2\[/g
-  / <<<$/s//\]$CR/g
-  /^\s\s\(.*\)$/s//$C10&$CR/
-  /(C|W):\s.*/s//$C13&$CR/
-  /(I|N):\s.*/s//$C6&$CR/
-  /.*\s-> L\s.*/s//$C4&$CR/
-  /.*\s-> C\s.*/s//$C3&$CR/
-  /\<(E|Err|Wrn|ERR):\s.*/s//$C1&$CR/
-";}
-
-# ======================================================================
 if [[ -z $DISPLAY ]]; then  # Use host xserver if SSH
     export DISPLAY=$(xauth list | sed -rn '1s/^[^:]*(:[0-9]+).*/\1/p')
 fi
@@ -53,9 +34,29 @@ if cfgOpt i && cfgOpt u && ((!$#)) && [[ ! -f "$queue" ]]; then
 fi
 
 # ======================================================================
+for n in {0..15}; do declare C${n}=$(tput setaf ${n:?}); done && CR=$(tput sgr0)
+header(){ printf "\n$C2>>> %s <<<$CR\n" "$1"; }
+pretty() { sed -r "
+  s|/home/$(whoami)|\~|g
+  s|\~/\S+/cfg/||g
+  />>>/!s|^|  |g
+  /^>>> \~\/aura\//s//\n$C9\[/g
+  /^>>> /s//\n$C2\[/g
+  / <<<$/s//\]$CR/g
+  /^\s\s\(.*\)$/s//$C10&$CR/
+  /(C|W):\s.*/s//$C13&$CR/
+  /(I|N):\s.*/s//$C6&$CR/
+  /.*\s-> L\s.*/s//$C4&$CR/
+  /.*\s-> C\s.*/s//$C3&$CR/
+  /\<(E|Err|Wrn|ERR):\s.*/s//$C1&$CR/
+";}
+
+# THINK:USE: exec > >(pretty)  (BUT: pacman -Syu output, jobs, etc?)
+exec > >(pretty)
+# ======================================================================
 ## Setup all configs (private data must be initialized already)
-prf="${CURR_DIR_CACHE:?}/profile"  # Populate private env
-[[ $prf ]] && source "$prf" || echo "Wrn: not found '$prf'" | pretty
+prf=${CURR_DIR_CACHE:?}/profile  # Populate private env
+[[ -f $prf ]] && source "$prf" || echo "Wrn: not found '$prf'"
 
 frgx(){ local patt="\\b$*\\b"
     [[ "$*" =~ ^/$ ]] && patt="cfg" ||:
@@ -92,7 +93,7 @@ fi
 
 # ======================================================================
 # EXPL: -m (in main 'setup') forces single thread execution
-run(){ [[ -f "$1" ]] && "$@" $(cfgOpt m || echo -m) || echo "(no ${1##*/})"; }
+run(){ if [[ -f $1 ]]; then "$@" $(cfgOpt m || echo -m); else echo "(no ${1##*/})"; fi; }
 r_install(){ cfgOpt i || return 0; run "$1/install" $(cfgOpt f && echo -u); }
 r_setup(){ run "$1/setup" $(cfgOpt u && echo -u); }
 
@@ -107,7 +108,7 @@ while read d; do echo ">>> $d <<<"
     r_setup "$d"
     sed -i '1d' "$queue"
 # EXPL: copy $queue content to be not affected by 'sed'
-done <<< "$(<"$queue")" | pretty
+done <<< "$(<"$queue")"
 rm "$queue"
 
 # ======================================================================
