NOTE filesystems, FIX minor

diff --git a/cfg/shell/func.d/system b/cfg/shell/func.d/system
--- a/cfg/shell/func.d/system
+++ b/cfg/shell/func.d/system
@@ -8,13 +8,19 @@ distro(){ cat /etc/os-release | grep -iq "$1"; }
 has_pr(){ hash $1 >/dev/null 2>&1; }
 do_sleep() { sleep "$1" & { while kill -0 $! >/dev/null 2>&1; do printf "."; sleep 0.5; done; echo; }; }
 
-squit() { printf "${1+$1\n}"; if [ -n "$PS1" ]; then return ${1+1}; else exit ${1+1}; fi; }
+die() { local ret=$?
+    if [[ "$1" =~ [0-9]+ ]]; then ret=$1; shift; fi
+    printf "%s${1+\n}" "$1"
+    # For case when you source this functions to interactive shell
+    [[$PS1]] && return $ret || exit $ret
+}
+
 amAskConfirm() {
     printf "$1\n"
     read answer
     case $answer in
         [yY] | [yY][Ee][Ss] ) return 0 ;;
-        [nN] | [n|N][O|o] ) squit "Rejected" ;;
-        *) squit "Invalid input" ;;
+        [nN] | [n|N][O|o] ) die "Rejected" ;;
+        *) die "Invalid input" ;;
     esac
 }
