[ranger] use bat for syntax hi in preview

diff --git a/dlt/ctl/table-join b/dlt/ctl/table-join
--- a/dlt/ctl/table-join
+++ b/dlt/ctl/table-join
@@ -1,2 +1,6 @@
-#!/bin/zsh -eu
-r.dlt-view $@ -- *.dlt*(.On) >! ${$(echo *.dlt)%.dlt}.txt
+#!/bin/zsh
+set -euo nullglob
+fs=( dlt_*.[0-9].dlt(.On) dlt_*[^.]?.dlt )
+(( $#fs )) || { echo "Err: *.dlt not found" >&2; exit 1; }
+exec r.dlt-view $@ -- $fs >! dlt.txt
+# r.dlt-view $@ -- *.dlt*(.On) >! ${$(echo *.dlt)%.dlt}.txt
